[2022-12-04 05:12:05,449] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2022-12-04T05:10:32.775557+00:00 [queued]>
[2022-12-04 05:12:05,475] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2022-12-04T05:10:32.775557+00:00 [queued]>
[2022-12-04 05:12:05,476] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 05:12:05,476] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-04 05:12:05,476] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 05:12:05,498] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-12-04 05:10:32.775557+00:00
[2022-12-04 05:12:05,509] {standard_task_runner.py:52} INFO - Started process 1936 to run task
[2022-12-04 05:12:05,512] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_dataset_task', 'manual__2022-12-04T05:10:32.775557+00:00', '--job-id', '204', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp_rwogt0v', '--error-file', '/tmp/tmpz4dvgpjl']
[2022-12-04 05:12:05,513] {standard_task_runner.py:77} INFO - Job 204: Subtask download_dataset_task
[2022-12-04 05:12:05,580] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2022-12-04T05:10:32.775557+00:00 [running]> on host f96e892f1d4c
[2022-12-04 05:12:05,660] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-04T05:10:32.775557+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-04T05:10:32.775557+00:00
[2022-12-04 05:12:05,662] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-04 05:12:05,663] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl https://datausa.io/api/data?drilldowns=Nation&measures=Population > /opt/***/nation_population.json']
[2022-12-04 05:12:05,692] {subprocess.py:85} INFO - Output:
[2022-12-04 05:12:05,706] {subprocess.py:89} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2022-12-04 05:12:05,706] {subprocess.py:89} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2022-12-04 05:12:05,754] {subprocess.py:89} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100    52  100    52    0     0   1040      0 --:--:-- --:--:-- --:--:--  1040
[2022-12-04 05:12:05,756] {subprocess.py:89} INFO - {"error":"Query must contain at least one measure."}
[2022-12-04 05:12:05,757] {subprocess.py:93} INFO - Command exited with return code 0
[2022-12-04 05:12:05,795] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20221204T051032, start_date=20221204T051205, end_date=20221204T051205
[2022-12-04 05:12:05,852] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-04 05:12:05,966] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
